# Generated by Django 3.2.10 on 2023-06-27 20:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ThrottleAction', '0002_auto_20230628_0211'),
    ]

    operations = [
        migrations.RenameField(
            model_name='reviews',
            old_name='Introduction',
            new_name='content',
        ),
    ]
