# Generated by Django 3.2.10 on 2023-06-27 20:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ThrottleAction', '0003_rename_introduction_reviews_content'),
    ]

    operations = [
        migrations.RenameField(
            model_name='exclusive',
            old_name='Introduction',
            new_name='content',
        ),
    ]
