# Generated by Django 3.2.10 on 2023-06-28 20:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ThrottleAction', '0004_rename_introduction_exclusive_content'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contact',
            name='Question',
            field=models.CharField(blank=True, max_length=2555555555, null=True),
        ),
    ]
